FROM ubi8/ubi:8.3

MAINTAINER Thiago-RM341691-Grupo32 <pessaicow@hotmail.com>

LABEL description="A custom Apache container based on UBI 8"

RUN yum install -y httpd && \
    yum clean all

RUN echo "Hello from Grupo32 RM341691" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]